### ISSUE TITLE
Test Case 4: Patient Search feature

### ISSUE THREAD

**Issue by moshonk** [IsantePlus/isanteplus-qaframework#10]
Search using First and Last Name
Search using ST code
Search using Fingerprint

see more https://paper.dropbox.com/doc/iSantePlus-System-Testing-Protocol-ZcIECdRoBfKswXOFKnWqS

**Comment by sherrif10** [comment]
https://github.com/IsantePlus/isanteplus-qaframework/pull/28    . We can close this ticket since it have been fixed
