### ISSUE TITLE
Search Patient Table should be clickable in findPatientPage

### ISSUE THREAD

**Issue by sherrif10** [IsantePlus/isanteplus-qaframework#12]
This fix is supposed to be in  coreapps module of the version that is running in the isantePlus system
While searching for a patient, after entering any given name, the patient search table should allow transitioning of patients, it should be clickable within the tables.. 

Steps to reproduce.

1. Login in the system
2. click on findPatient app
3. enter any given name in search box
4. try accessing the returned search box by clicking in the table. The table is clickable but it would be looking so advanced when these tables appear to be clickabe.
cc @mozzy11  @moshonk

**Comment by mozzy11** [comment]
@sherrif10  i dont this properly

**Comment by sherrif10** [comment]
> @sherrif10 i dont this properly

Login into the isante demo server https://isanteplus-test.sedish-haiti.org/openmrs/
Find a registered patient from the db
Then the system should return registered patient, upon clicking on the returned patient from the patient table, the clicker is not pointing to the patient, it is shown as if its clicking in the air not on the patient. Hope its clear now, we need to make it more vulnerable.

**Comment by moshonk** [comment]
@sherrif10 The issue raised, does not apply to this project. It was already created in the relevant project https://github.com/IsantePlus/openmrs-module-coreapps/issues/11
