### ISSUE TITLE
Test Case  3: Adding a Patient 

### ISSUE THREAD

**Issue by mozzy11** [IsantePlus/isanteplus-qaframework#14]
Automate " Adding a Patient " test case .
see test case 3 from the [test case document](https://paper.dropbox.com/doc/iSantePlus-System-Testing-Protocol-ZcIECdRoBfKswXOFKnWqS)

**Comment by sherrif10** [comment]
Isnt this already fixed here https://github.com/IsantePlus/isanteplus-qaframework/blob/main/src/test/java/org/openmrs/contrib/isanteplus/qaframework/automation/AddPatientSteps.java  . How do you see if we call it **registerPatient i**nstead of **addPatient**

**Comment by mozzy11** [comment]
lets simply follow the document to make it simple
this was just part of the work here https://github.com/IsantePlus/isanteplus-qaframework/pull/7.

we need to add the second scenario of Adding a Pediatric Patient

**Comment by sherrif10** [comment]
Sure  following the documents is priority but having clear definition of
classes also accounts I think.
