### ISSUE TITLE
Test Case 5 :  Patient Cover Sheet

### ISSUE THREAD

**Issue by mozzy11** [IsantePlus/isanteplus-qaframework#15]
Automate the " Patient Cover Sheet" test case 
see test case 5 from   [ the test case document](https://paper.dropbox.com/doc/iSantePlus-System-Testing-Protocol-ZcIECdRoBfKswXOFKnWqS)

**Comment by sherrif10** [comment]
This test is same as Patient summary   https://github.com/IsantePlus/isanteplus-qaframework/pull/46
